"""Add profile picture to Utilisateur

Revision ID: 4fb16d2b0aff
Revises: 25e91fecefdb
Create Date: 2024-11-20 01:06:02.527131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fb16d2b0aff'
down_revision = '25e91fecefdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('auteur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['auteur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suivis',
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_suivi', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_suivi'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('utilisateur_id', 'utilisateur_suivi')
    )
    op.drop_table('favoris')
    op.drop_table('commentaire')
    op.drop_table('film')
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_profil', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.drop_column('image_profil')

    op.create_table('film',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titre', sa.VARCHAR(length=100), nullable=False),
    sa.Column('genre', sa.VARCHAR(length=50), nullable=True),
    sa.Column('annee_sortie', sa.INTEGER(), nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commentaire',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('contenu', sa.TEXT(), nullable=False),
    sa.Column('date_creation', sa.DATETIME(), nullable=False),
    sa.Column('film_id', sa.INTEGER(), nullable=False),
    sa.Column('utilisateur_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favoris',
    sa.Column('film_id', sa.INTEGER(), nullable=False),
    sa.Column('utilisateur_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('film_id', 'utilisateur_id')
    )
    op.drop_table('suivis')
    op.drop_table('publication')
    # ### end Alembic commands ###
